package lol.vfs.routing

import io.ktor.server.auth.*

/**
 * Stored token used to authenticate a user
 * @param token Token generated by the backend to authenticate user
 */
data class UserSession(var id: String, var token: String) : Principal