package lol.vfs

import io.ktor.server.application.*
import io.ktor.server.auth.*
import io.ktor.server.response.*
import io.ktor.server.sessions.*

/**
 * Stored token used to authenticate a user
 * @param token Token generated by the backend to authenticate user
 */
data class LoginSession(var username: String, var token: String) : Principal

fun Application.authSetup() {
   install(Sessions) {
      cookie<LoginSession>("login-session")
   }
   install(Authentication) {
      session<LoginSession>("auth") {
         validate { session ->
            if (Database.checkToken(session.username, session.token))
               session
            else null

         }
         challenge {
            call.respondRedirect("/login")
         }

      }

   }

}

